"""
Invoice / AR-chase agent.

Runs daily. Queries the tenant's subscriptions + invoices tables to
find overdue invoices, drafts an escalating reminder, and:

  * day 1 overdue — auto-send polite reminder
  * day 3 overdue — auto-send firmer "your account will be suspended"
  * day 7+      — pending-approval action: founder sees the draft + customer history
                    before any further chase

Tone for each step is generated by the LLM in the founder's voice
(extracted from prior approved AR emails, when available, via the
'voice_examples' state key).

Why this is a measurable-ROI agent: recovers 15-30% more revenue than
no-chase, with zero founder time spent on dunning.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any

from agents.base import Agent, AgentAction, AgentContext, AgentResult
from agents.registry import register

log = logging.getLogger("agents.ar_chase")


SYSTEM_PROMPT = """You are an AR clerk for a SaaS founder. Draft a
payment-chase email. Tone scales with overdue days:

  day 1   — gentle: "we noticed payment didn't go through, here's the link"
  day 3   — firmer: "account access will pause if this isn't resolved by..."
  day 7+  — escalation: factual + concrete next step + founder review

Always:
  - Use the customer's first name if available.
  - Reference the invoice id + amount + new payment link.
  - Sign with the founder's first name.
  - Plain prose, no marketing speak.
  - <120 words.

Output exactly this JSON — no surrounding prose:

{
  "subject": "...",
  "body_md": "..."
}
"""


@register
class ArChaseAgent(Agent):
    NAME = "ar_chase"
    DESCRIPTION = (
        "Chases overdue customer invoices on your behalf. Day 1 + day 3 "
        "auto-send; day 7+ wait for your approval. Recovers ~20% more "
        "revenue than no-chase."
    )
    SCHEDULE = "daily"
    DEFAULT_ON_TIERS = ("launch", "growth")

    def run(self, ctx: AgentContext) -> AgentResult:
        overdue = self._fetch_overdue(ctx)
        if not overdue:
            return AgentResult(notes="No overdue invoices.",
                               metrics={"chased": 0})

        founder_first_name = ctx.state_get("founder_first_name", "")
        already_chased = set(ctx.state_get("chased_invoice_ids", []) or [])
        new_already_chased = set(already_chased)

        actions: list[AgentAction] = []
        n_auto = n_pending = 0
        total_overdue_pence = 0

        for inv in overdue:
            inv_id = str(inv["id"])
            days = int(inv["days_overdue"])
            total_overdue_pence += int(inv["amount_pence"])

            # Tone tier mapped to days. Dedup by (invoice, day-bucket) so
            # we only send one reminder per bucket per invoice.
            bucket = (
                "day_1" if days <= 2
                else "day_3" if days <= 5
                else "day_7"
            )
            key = f"{inv_id}:{bucket}"
            if key in already_chased:
                continue

            draft = self._draft_chase(ctx, inv, bucket, founder_first_name)
            if not draft:
                continue

            requires_approval = bucket == "day_7"
            actions.append(AgentAction(
                kind="send_email", requires_approval=requires_approval,
                summary=(
                    f"AR chase ({bucket}) — £{inv['amount_pence']/100:.2f} "
                    f"overdue {days}d from {inv['customer_email']}"
                ),
                payload={
                    "to": inv["customer_email"],
                    "subject": draft.get("subject", "Payment reminder"),
                    "body_md": draft.get("body_md", ""),
                    "from_name": founder_first_name or "Accounts",
                    "__slug": ctx.slug, "__invoice_id": inv_id, "__bucket": bucket,
                },
                rationale=f"invoice overdue {days} days",
                confidence=1.0 if not requires_approval else 0.7,
            ))
            new_already_chased.add(key)
            if requires_approval:
                n_pending += 1
            else:
                n_auto += 1

        ctx.state_set("chased_invoice_ids", sorted(new_already_chased))
        notes = (
            f"{len(overdue)} overdue invoice(s) totalling "
            f"£{total_overdue_pence/100:.2f}. "
            f"Sent {n_auto} reminders, escalated {n_pending}."
        )
        return AgentResult(
            actions=actions, notes=notes,
            metrics={
                "overdue_invoices": len(overdue),
                "overdue_amount_pence": total_overdue_pence,
                "auto_sent": n_auto, "escalated": n_pending,
            },
        )

    # ─── Helpers ──────────────────────────────────────────────────────
    def _fetch_overdue(self, ctx: AgentContext) -> list[dict[str, Any]]:
        """Pull overdue invoices from the substrate's invoices table.

        Substrate schema (created at provisioning): invoices(
          id, customer_email, amount_pence, due_at, paid_at, status
        ).
        """
        rows = ctx.tenant_db(
            "SELECT id, customer_email, amount_pence, "
            "EXTRACT(DAY FROM now() - due_at)::int AS days_overdue "
            "FROM invoices "
            "WHERE status = 'unpaid' AND due_at < now() - interval '1 day' "
            "ORDER BY due_at LIMIT 50",
        )
        out = []
        for r in rows:
            cols = r.get("row") or []
            if "error" in r or len(cols) < 4:
                continue
            try:
                out.append({
                    "id": cols[0], "customer_email": cols[1],
                    "amount_pence": int(cols[2]),
                    "days_overdue": int(cols[3]),
                })
            except (ValueError, IndexError):
                continue
        return out

    def _draft_chase(
        self, ctx: AgentContext, inv: dict[str, Any],
        bucket: str, founder_first_name: str,
    ) -> dict[str, Any] | None:
        user = (
            f"FOUNDER FIRST NAME: {founder_first_name or '(unknown)'}\n"
            f"CHASE TIER: {bucket}\n\n"
            f"INVOICE:\n"
            f"  id: {inv['id']}\n"
            f"  customer: {inv['customer_email']}\n"
            f"  amount: £{inv['amount_pence']/100:.2f}\n"
            f"  days overdue: {inv['days_overdue']}\n"
            f"  payment link: https://{ctx.slug}.hatchik.com/billing/pay/{inv['id']}"
        )
        try:
            response = ctx.llm(
                system=SYSTEM_PROMPT, user=user,
                model="claude-haiku-4-5", max_tokens=350,
            )
        except Exception as e:  # noqa: BLE001
            log.warning("AR draft LLM failed: %s", e)
            return None
        text = self._extract_text(response)
        try:
            return json.loads(text[text.index("{"):text.rindex("}") + 1])
        except (ValueError, json.JSONDecodeError):
            return None

    def _extract_text(self, response: dict[str, Any]) -> str:
        content = response.get("content")
        if isinstance(content, list) and content:
            first = content[0]
            if isinstance(first, dict) and first.get("type") == "text":
                return first.get("text", "")
        choices = response.get("choices")
        if isinstance(choices, list) and choices:
            msg = choices[0].get("message") or {}
            return msg.get("content", "")
        return ""
